def netSplode(contextId, 
	environmentCode,
	contextName,
	contextType,
	eventIP,
	eventSession,
	eventAction,
	eventObject,
	eventURL,
	eventAuthorID,
	eventAuthorName,
	eventDate,
	objectCreator,
	parentId):
   